### PR TITLE
because docker is now 1.7.1 on default ami

### PR DESCRIPTION
**Pull request by cordoval**
solves this https://github.com/remind101/conveyor/issues/44

### CODE REVIEW

**Comment by ejholmes** [comment]
Hmm, doesn't this need support in the [docker builder](https://github.com/remind101/conveyor/blob/17c54b3c0363606a08e603f6c34d4d56cf8e79a7/builder/docker/bin/build#L63) as well? Right now, it tries to copy `/var/run/conveyor/.dockercfg`, which wouldn't exist with this change.

**Comment by cordoval** [comment]
true, i will change it, any other place i have missed? cc @ejholmes

**Comment by cordoval** [comment]
updated @ejholmes

**Comment by cordoval** [comment]
rebased @ejholmes , what are the ways you try things on your end? i am curious, i sometimes try stuff and it does not work

**Comment by ejholmes** [comment]
Testing the builder is a little tricky because it currently relies on pulling from a github repo and pushing to a docker repo. You have to run `make bootstrap` in the `builder/docker` then upload the ssh key to your github account, then run `make test`. I want to get this running in CI so it's at least tested there.

**Comment by cordoval** [comment]
rebased @ejholmes i will test in a bit by hand

**Comment by cordoval** [comment]
this one is hard to test because the image that is spawn by this is not pushed to dockerhub and is not the remind101/conveyor image

**Comment by ejholmes** [comment]
This looks good to me. I'll merge and build a new version of `remind101/conveyor-builder`.

**Comment by cordoval** [comment]
Thanks man, it feels good! :+1:

**Pull request merged**
