### PR TITLE
Fixing typos when setting the SQS_QUEUE_URL and QUEUE env vars.

### PR DESCRIPTION
**Pull request by russ**
Fix for some minor typos.

### CODE REVIEW

**Comment by ejholmes** [comment]
Awesome! Thanks for this! I'll be testing this out soon.

**Comment by cordoval** [comment]
bump @ejholmes i ran into this as well

**Comment by cordoval** [comment]
These changes should be straightforward i believe :+1:

**Comment by ejholmes** [comment]
Sorry for the delay! This is fixed with https://github.com/remind101/conveyor/commit/17c54b3c0363606a08e603f6c34d4d56cf8e79a7 on master.

**Pull request closed without merging**
